### PR TITLE
Fix essentia search NPE

### LINKED ISSUE #18017: findIt crash when searching nearby containers for thaumcraft knowledge fragments ("stackAspects" is null)
### Your GTNH Discord Username

.flaxo

### Your Pack Version

2.7.0-nightly-2024-11-11

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Using findIt to try and locate knowledge fragments from thaumcraft in nearby containers causes a crash to menu screen

### Crash Report

https://mclo.gs/NqsBdB9

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

### LINKED ISSUE #18034: FindIt + Thaumcraft still crashing when aspect containing items are in a container
### Your GTNH Discord Username

_No response_

### Your Pack Version

2.7.0-beta4

### Your Server

Private server

### Java Version

Java 21

### Type of Server

None

### Your Actions

Search for enchanted fabric in a chest
Then the next chest I open contains phials of essentia (while findit is still "hot")
image

This also works with crystallized essentia, mana beans, and ethereal essence,

### Crash Report

https://mclo.gs/iC6HYLN
https://mclo.gs/JJbNmzJ

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

### PR DESCRIPTION
**Pull request by wlhlm**
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18034
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18017

### CODE REVIEW

**Review by slprime — APPROVED** [review]

**Comment by slprime** [comment]
@wlhlm why in draft? it fixed bug

How to check: add "Enchanted Fabric" in chest and try find it

**Comment by wlhlm** [comment]
I actually wasn't able to reproduce the crash, so I'm currently waiting for the reporters to confirm.

**Comment by slprime** [comment]
> I actually wasn't able to reproduce the crash, so I'm currently waiting for the reporters to confirm.

Add "Phial of Essentia" and  "Enchanted Fabric"  in chest and try find "Enchanted Fabric"

**Comment by wlhlm** [comment]
Yep, thanks for the guide. I can reproduce now and this PR fixes it.

**Pull request merged**
