### PR TITLE
Improvements and fixes

### PR DESCRIPTION
**Pull request by socolio**
* Add support of almost all fluid tanks
image

* Add highlighting of dropped items (configurable, enabled by default)
image

* Block highlight box now equal to block selection shape (if it is big enough) + special handling of double chests
image

* Fix nearest block calculation to look at
* Fix slot highlight render with Angelica (it was affected by gl lighting)
* Add config option to search items & fluid in GT pipes (disabled by default)
* Code refactoring

### CODE REVIEW

**Comment by Caedis** [comment]
Have you tested this in the full pack?

**Comment by socolio** [comment]
> Have you tested this in the full pack?

Yes. All screenshots were taken from GTNH

**Comment by Caedis** [comment]
Can you add a screenshot of it finding a fluid in GT pipes?

**Comment by socolio** [comment]
> Can you add a screenshot of it finding a fluid in GT pipes?

maybe i should also add config option for fluid conduits... sad story of adding support for all fluid tanks & handlers
image

**Comment by socolio** [comment]
> > Can you add a screenshot of it finding a fluid in GT pipes?
> 
> image

maybe i should also add config option for fluid conduits...

**Comment by socolio** [comment]
Fluid Conduits fixed
image

**Comment by Caedis** [comment]
Have you tested this in the full pack with angelica?
Specifically the latest nightly

**Comment by socolio** [comment]
> nightly

Tested on one of the latest 2.7.0 nightly builds with Angelica-alpha50. Everything works fine.

**Comment by socolio** [comment]
> Have you tested this in the full pack with angelica? Specifically the latest nightly

Tested on one of the latest 2.7.0 nightly builds with Angelica-alpha50. Everything works fine.

**Review by Caedis — APPROVED** [review]

**Comment by leumasme** [comment]
image

unlike your screenshot, the item outline appears to be ~50% too high for me. this happens even when checking out the commit where this pr was merged, as well as in full pack nightlies. what happened?

**Comment by leumasme** [comment]
Looks like it works fine on dropped items but is offset for dropped blocks.

**Pull request merged**
